/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#c0000c",
        "on-primary-fixed-variant": "#930007",
        "on-primary-fixed": "#410001",
        "tertiary": "#a7c8ff",
        "on-error": "#690005",
        "outline": "#af8782",
        "primary-container": "#e50914",
        "surface-variant": "#353534",
        "secondary-container": "#921512",
        "on-secondary-fixed": "#410001",
        "surface-container-lowest": "#0e0e0e",
        "on-surface": "#e5e2e1",
        "surface-dim": "#131313",
        "surface-container": "#201f1f",
        "on-primary-container": "#fff7f6",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed": "#ffdad5",
        "primary-fixed": "#ffdad5",
        "inverse-surface": "#e5e2e1",
        "error-container": "#93000a",
        "on-tertiary-container": "#f8f9ff",
        "on-background": "#e5e2e1",
        "primary-fixed-dim": "#ffb4aa",
        "error": "#ffb4ab",
        "on-primary": "#690003",
        "background": "#131313",
        "on-secondary": "#690003",
        "tertiary-fixed-dim": "#a7c8ff",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed-variant": "#8e1210",
        "on-tertiary-fixed-variant": "#004689",
        "tertiary-fixed": "#d5e3ff",
        "secondary-fixed-dim": "#ffb4aa",
        "surface-container-low": "#1c1b1b",
        "on-tertiary": "#003061",
        "surface-bright": "#3a3939",
        "on-tertiary-fixed": "#001b3c",
        "surface-tint": "#ffb4aa",
        "surface-container-highest": "#353534",
        "tertiary-container": "#0072d7",
        "on-surface-variant": "#e9bcb6",
        "secondary": "#ffb4aa",
        "primary": "#ffb4aa",
        "on-secondary-container": "#ff9f93",
        "outline-variant": "#5e3f3b",
        "surface": "#131313"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"],
        "manrope": ["Manrope"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
